
[build.nixpacksPlan.phases.setup]
nixPkgs = ["...", "yt-dlp"]

[build]
installCommand = "ls" # Specify any additional install commands if necessary
buildCommand = "echo 'Build step complete'" # If no build step is needed

[deploy]
startCommand = "bun build/app" # Replace 'your_executable' with the actual executable you want to run
